library:
  source-dirs: src
tests:
  slurm-proposals-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slurm-proposals
    - hspec
copyright: 2019 Barry Moore II
maintainer: moore0557@gmail.com
dependencies:
- text
- base >= 4.7 && < 5
- beam-core
- beam-sqlite
- beam-migrate
- sqlite-simple
- time
name: slurm-proposals
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Barry Moore II
github: barrymoo/slurm-proposals
license: MIT
executables:
  slurm-proposals-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slurm-proposals
description: Please see the README on GitHub at <https://github.com/barrymoo/slurm-proposals#readme>
