name: Haskell Stack Project CI

on: [push, pull_request]

jobs:
  build:
    name: Try building project
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install haskell-stack
      - run: stack upgrade
      - run: stack update
      - run: stack build
      - run: stack test
